"""Create a local .streamlit/secrets.toml for admin/engineer accounts.

Run locally after installing requirements:
    python setup_users.py

The generated secrets.toml is gitignored and should not be committed.
"""
from pathlib import Path
import getpass
import bcrypt

USERS = [("admin", "admin"), ("engineer1", "engineer"), ("engineer2", "engineer")]


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode("utf-8")


def main() -> None:
    blocks = ["# Generated by setup_users.py. NEVER commit this file to GitHub.\n"]
    for username, role in USERS:
        while True:
            p1 = getpass.getpass(f"Password for {username}: ")
            p2 = getpass.getpass(f"Confirm password for {username}: ")
            if p1 and p1 == p2:
                break
            print("Passwords did not match or were blank. Try again.")
        blocks += [
            f"[auth.users.{username}]",
            f'role = "{role}"',
            f'password_hash = "{hash_password(p1)}"',
            "",
        ]

    out = Path(".streamlit/secrets.toml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(blocks), encoding="utf-8")
    print(f"Created {out}. Keep it private and copy its contents to Streamlit Cloud Secrets.")


if __name__ == "__main__":
    main()
